# About this Notebook
This notebook will generate the list of top cuisine types for each country based on Google place types and JET restaurant dim table.
The output of this notebook will be used to subset and aggregate cuisine types of those markets for the lead scoring model.

In [1]:
!pip install fsspec gcsfs seaborn

Requirement already satisfied: fsspec in /opt/micromamba/envs/MLP-generic/lib/python3.9/site-packages (2025.3.2)
Requirement already satisfied: gcsfs in /opt/micromamba/envs/MLP-generic/lib/python3.9/site-packages (2025.3.2)
Requirement already satisfied: seaborn in /opt/micromamba/envs/MLP-generic/lib/python3.9/site-packages (0.13.2)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /opt/micromamba/envs/MLP-generic/lib/python3.9/site-packages (from gcsfs) (3.11.18)
Requirement already satisfied: decorator>4.1.2 in /opt/micromamba/envs/MLP-generic/lib/python3.9/site-packages (from gcsfs) (5.1.1)
Requirement already satisfied: google-auth>=1.2 in /opt/micromamba/envs/MLP-generic/lib/python3.9/site-packages (from gcsfs) (2.38.0)
Requirement already satisfied: google-auth-oauthlib in /opt/micromamba/envs/MLP-generic/lib/python3.9/site-packages (from gcsfs) (1.2.1)
Requirement already satisfied: google-cloud-storage in /opt/micromamba/envs/MLP-generic/lib/python3.9/site-packages (from gcsfs) (2.19.0)
Requirement already satisfied: requests in /opt/micromamba/envs/MLP-generic/lib/python3.9/site-packages (from gcsfs) (2.32.3)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in /opt/micromamba/envs/MLP-generic/lib/python3.9/site-packages (from seaborn) (2.0.2)
Requirement already satisfied: pandas>=1.2 in /opt/micromamba/envs/MLP-generic/lib/python3.9/site-packages (from seaborn) (2.2.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /opt/micromamba/envs/MLP-generic/lib/python3.9/site-packages (from seaborn) (3.8.4)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /opt/micromamba/envs/MLP-generic/lib/python3.9/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->gcsfs) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in /opt/micromamba/envs/MLP-generic/lib/python3.9/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->gcsfs) (1.3.2)
Requirement already satisfied: async-timeout<6.0,>=4.0 in /opt/micromamba/envs/MLP-generic/lib/python3.9/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->gcsfs) (5.0.1)
Requirement already satisfied: attrs>=17.3.0 in /opt/micromamba/envs/MLP-generic/lib/python3.9/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->gcsfs) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /opt/micromamba/envs/MLP-generic/lib/python3.9/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->gcsfs) (1.6.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /opt/micromamba/envs/MLP-generic/lib/python3.9/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->gcsfs) (6.4.3)
Requirement already satisfied: propcache>=0.2.0 in /opt/micromamba/envs/MLP-generic/lib/python3.9/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->gcsfs) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /opt/micromamba/envs/MLP-generic/lib/python3.9/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->gcsfs) (1.20.0)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /opt/micromamba/envs/MLP-generic/lib/python3.9/site-packages (from google-auth>=1.2->gcsfs) (5.5.1)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /opt/micromamba/envs/MLP-generic/lib/python3.9/site-packages (from google-auth>=1.2->gcsfs) (0.4.1)
Requirement already satisfied: rsa<5,>=3.1.4 in /opt/micromamba/envs/MLP-generic/lib/python3.9/site-packages (from google-auth>=1.2->gcsfs) (4.9)
Requirement already satisfied: contourpy>=1.0.1 in /opt/micromamba/envs/MLP-generic/lib/python3.9/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.0)
Requirement already satisfied: cycler>=0.10 in /opt/micromamba/envs/MLP-generic/lib/python3.9/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /opt/micromamba/envs/MLP-generic/lib/python3.9/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.55.4)
Requirement already satisfied: kiwisolver>=1.3.1 in /opt/micromamba/envs/MLP-generic/lib/python3.9/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.7)
Requirement already satisfied: packaging>=20.0 in /opt/micromamba/envs/MLP-generic/lib/python3.9/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (24.2)
Requirement already satisfied: pillow>=8 in /opt/micromamba/envs/MLP-generic/lib/python3.9/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in /opt/micromamba/envs/MLP-generic/lib/python3.9/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.2.1)
Requirement already satisfied: python-dateutil>=2.7 in /opt/micromamba/envs/MLP-generic/lib/python3.9/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: importlib-resources>=3.2.0 in /opt/micromamba/envs/MLP-generic/lib/python3.9/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (6.5.2)
Requirement already satisfied: pytz>=2020.1 in /opt/micromamba/envs/MLP-generic/lib/python3.9/site-packages (from pandas>=1.2->seaborn) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/micromamba/envs/MLP-generic/lib/python3.9/site-packages (from pandas>=1.2->seaborn) (2025.1)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /opt/micromamba/envs/MLP-generic/lib/python3.9/site-packages (from google-auth-oauthlib->gcsfs) (2.0.0)
Requirement already satisfied: google-api-core<3.0.0dev,>=2.15.0 in /opt/micromamba/envs/MLP-generic/lib/python3.9/site-packages (from google-cloud-storage->gcsfs) (2.24.0)
Requirement already satisfied: google-cloud-core<3.0dev,>=2.3.0 in /opt/micromamba/envs/MLP-generic/lib/python3.9/site-packages (from google-cloud-storage->gcsfs) (2.4.1)
Requirement already satisfied: google-resumable-media>=2.7.2 in /opt/micromamba/envs/MLP-generic/lib/python3.9/site-packages (from google-cloud-storage->gcsfs) (2.7.2)
Requirement already satisfied: google-crc32c<2.0dev,>=1.0 in /opt/micromamba/envs/MLP-generic/lib/python3.9/site-packages (from google-cloud-storage->gcsfs) (1.6.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/micromamba/envs/MLP-generic/lib/python3.9/site-packages (from requests->gcsfs) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /opt/micromamba/envs/MLP-generic/lib/python3.9/site-packages (from requests->gcsfs) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/micromamba/envs/MLP-generic/lib/python3.9/site-packages (from requests->gcsfs) (1.26.20)
Requirement already satisfied: certifi>=2017.4.17 in /opt/micromamba/envs/MLP-generic/lib/python3.9/site-packages (from requests->gcsfs) (2024.12.14)
Requirement already satisfied: googleapis-common-protos<2.0.dev0,>=1.56.2 in /opt/micromamba/envs/MLP-generic/lib/python3.9/site-packages (from google-api-core<3.0.0dev,>=2.15.0->google-cloud-storage->gcsfs) (1.66.0)
Requirement already satisfied: protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0.dev0,>=3.19.5 in /opt/micromamba/envs/MLP-generic/lib/python3.9/site-packages (from google-api-core<3.0.0dev,>=2.15.0->google-cloud-storage->gcsfs) (3.20.3)
Requirement already satisfied: proto-plus<2.0.0dev,>=1.22.3 in /opt/micromamba/envs/MLP-generic/lib/python3.9/site-packages (from google-api-core<3.0.0dev,>=2.15.0->google-cloud-storage->gcsfs) (1.25.0)
Requirement already satisfied: zipp>=3.1.0 in /opt/micromamba/envs/MLP-generic/lib/python3.9/site-packages (from importlib-resources>=3.2.0->matplotlib!=3.6.1,>=3.4->seaborn) (3.21.0)
Requirement already satisfied: typing-extensions>=4.1.0 in /opt/micromamba/envs/MLP-generic/lib/python3.9/site-packages (from multidict<7.0,>=4.5->aiohttp!=4.0.0a0,!=4.0.0a1->gcsfs) (4.12.2)
Requirement already satisfied: pyasn1<0.7.0,>=0.4.6 in /opt/micromamba/envs/MLP-generic/lib/python3.9/site-packages (from pyasn1-modules>=0.2.1->google-auth>=1.2->gcsfs) (0.6.1)
Requirement already satisfied: six>=1.5 in /opt/micromamba/envs/MLP-generic/lib/python3.9/site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Requirement already satisfied: oauthlib>=3.0.0 in /opt/micromamba/envs/MLP-generic/lib/python3.9/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib->gcsfs) (3.2.2)

In [13]:
from google.cloud import bigquery
import pandas as pd
import numpy as np
from datetime import datetime
from google.cloud import storage
import re
pd.set_option('display.max_rows', 500)


project_name = 'just-data-sa-dev'
today_date = datetime.today()

client = bigquery.Client(project=project_name, location="EU")

In [3]:

def download_latest_csv(bucket_name, top_level_folder, prefix, contains_pattern, destination_filename):
    """Downloads the latest CSV file from a GCS bucket based on a name prefix.

    Args:
        bucket_name (str): The name of the Google Cloud Storage bucket.
        top_level_folder (str): The top-level folder within the bucket to search.
        prefix (str): The prefix that the desired CSV file names start with.

    Returns:
        str: The local path where the latest CSV file is downloaded, or None if no matching file is found.
    """
    storage_client = storage.Client()
    bucket = storage_client.bucket(bucket_name)
    folder_path = f"{top_level_folder}/"
    blobs = bucket.list_blobs(prefix=folder_path)

    latest_blob = None
    latest_timestamp = None

    for blob in blobs:
        if blob.name.startswith(f"{folder_path}{prefix}") and (contains_pattern in blob.name) and blob.name.endswith("output_data"):
            # Extract timestamp from the folder name:
            match = re.search(r'(\d{14})', blob.name)
            if match:
                try:
                    timestamp_str = match.group(1)
                    blob_timestamp = datetime.strptime(timestamp_str, '%Y%m%d%H%M%S')
                    if latest_timestamp is None or blob_timestamp > latest_timestamp:
                        latest_timestamp = blob_timestamp
                        latest_blob = blob
                except ValueError:
                    print(f"Could not parse timestamp from blob name: {blob.name}")
    
    if latest_blob:
        destination_file_name = f"{destination_filename}.csv"
        latest_blob.download_to_filename(destination_file_name)
        print(f"Downloaded the latest CSV file: {latest_blob.name} to {destination_file_name}")
        return destination_file_name
    else:
        print(f"No CSV files found with prefix '{prefix}' in {bucket_name}/{top_level_folder}/")
        return None

## Download

In [18]:


# #jet-ml-prod-project-sa-lead-scoring/555228168644/sa-lead-scoring-20250506041002/read-data-2_-1566084851537281024
# bucket_name = "jet-ml-prod-project-sa-lead-scoring"
# top_level_folder = "555228168644"
# prefix = "sa-lead-scoring-"  # Assuming the CSV file name starts with this
# contains_pattern = "read-data-2_"
# destination_filename = "sa-lead-scoring-leads-data"

# downloaded_file_path = download_latest_csv(bucket_name, top_level_folder, prefix, contains_pattern, destination_filename)

# if downloaded_file_path:
#     print(f"Latest CSV file downloaded to: {downloaded_file_path}")

In [19]:
# #gs://jet-ml-prod-project-sa-lead-scoring/555228168644/sa-lead-scoring-20250506041002/read-data_7657287185317494784/output_data 
# bucket_name = "jet-ml-prod-project-sa-lead-scoring"
# top_level_folder = "555228168644"
# prefix = "sa-lead-scoring-"  # Assuming the CSV file name starts with this
# contains_pattern = "read-data_"
# destination_filename = "sa-lead-scoring-train-data"

# downloaded_file_path = download_latest_csv(bucket_name, top_level_folder, prefix, contains_pattern, destination_filename)

# if downloaded_file_path:
#     print(f"Latest CSV file downloaded to: {downloaded_file_path}")

In [20]:
# df_cuisine_leads = pd.read_csv("sa-lead-scoring-leads-data.csv")
# df_cuisine_train = pd.read_csv("sa-lead-scoring-train-data.csv")
# df_cuisine = pd.concat([df_cuisine_leads, df_cuisine_train])

In [21]:
# Load cuisine matching output data
query = """
    SELECT *
    FROM `just-data-warehouse.sales_data_science.cuisine_match_output`
"""
query_job = client.query(query)
df_cuisine = query_job.to_dataframe()

## Group cuisine types into major ones and 'other' type

In [24]:

MINOR_CUISINE_PCT = 0.001
MINOR_CUISINE_COUNT = 100
def group_minor_cuisine(df: pd.DataFrame):
    """If certain cuisine type has less than 100 places and contributes for less than 0.1% of all places in the country, group them under 'other' cuisine."""
    
    # Calculate counts and contributions
    country_counts = df.groupby(["country"], as_index=False).agg(country_total=("google_place_id", "nunique"))
    country_cuisine_counts = df.groupby(["country", "primary_cuisine"], as_index=False).agg(
        place_count=("google_place_id", "nunique")
    )

    cuisine_pct = country_cuisine_counts.merge(country_counts, how="left", on="country")
    cuisine_pct["count_pct"] = cuisine_pct["place_count"] / cuisine_pct["country_total"]

    # Map cuisines to 'other' if they meet criteria
    cuisine_pct["primary_cuisine_new"] = np.where(
        (cuisine_pct["count_pct"] < MINOR_CUISINE_PCT) & (cuisine_pct["place_count"] < MINOR_CUISINE_COUNT),
        "other",
        cuisine_pct["primary_cuisine"],
    )
    
    # Map unclear cuisines to other as well
    cuisine_pct["primary_cuisine_new"] = cuisine_pct["primary_cuisine_new"].replace(
        {"No matching cuisine": 'other', 
         "Unclear cuisine from Google": 'other',
        })
    
    cuisine_pct = cuisine_pct[["country", "primary_cuisine", "primary_cuisine_new"]]
    

    # Update original DataFrame
    df = df.merge(cuisine_pct, how="left", on=["country", "primary_cuisine"])
    
    df["primary_cuisine"] = df["primary_cuisine_new"]
    
    df.drop(columns=["primary_cuisine_new"], inplace=True)

    return df

In [25]:
df_cuisine = group_minor_cuisine(df_cuisine)

In [30]:
# Visualize statistics by the aggregated types
df_total_cuisine = df_cuisine.groupby(['country'], as_index=False).agg(cuisine_count=('google_place_id', 'nunique'))
df_cuisine_agg = df_cuisine.groupby(['country', 'primary_cuisine'], as_index=False).agg({'google_place_id':'nunique'})
df_cuisine_agg = df_cuisine_agg.merge(df_total_cuisine[['country', 'cuisine_count']], how='left', on=['country'])
df_cuisine_agg['count_pct'] = df_cuisine_agg['google_place_id']/df_cuisine_agg['cuisine_count']

In [31]:
check_country = 'IT'
df_cuisine_agg.loc[df_cuisine_agg['country']==check_country].sort_values('count_pct', ascending=False)

    country primary_cuisine  google_place_id  cuisine_count  count_pct
680      IT           pizza             5189          12237   0.424042
677      IT           other             1486          12237   0.121435
663      IT       fast food              968          12237   0.079104
689      IT           sushi              874          12237   0.071423
649      IT             bar              489          12237   0.039961
685      IT        sandwich              369          12237   0.030154
652      IT          burger              368          12237   0.030073
672      IT           kebab              226          12237   0.018469
670      IT         italian              224          12237   0.018305
681      IT       poke bowl              186          12237   0.015200
658      IT    delicatessen              159          12237   0.012993
656      IT         chinese              152          12237   0.012421
688      IT     supermarket              131          12237   0.010705
671      IT        japanese              122          12237   0.009970
667      IT         grocery              116          12237   0.009479
686      IT         seafood              113          12237   0.009234
648      IT          bakery               90          12237   0.007355
665      IT       gastropub               73          12237   0.005966
653      IT            cafe               71          12237   0.005802
661      IT           drink               57          12237   0.004658
657      IT          coffee               56          12237   0.004576
660      IT           diner               54          12237   0.004413
678      IT           pasta               50          12237   0.004086
669      IT          indian               49          12237   0.004004
664      IT          fusion               44          12237   0.003596
682      IT           ramen               40          12237   0.003269
654      IT       cafeteria               37          12237   0.003024
691      IT             tea               36          12237   0.002942
659      IT         dessert               35          12237   0.002860
675      IT         mexican               30          12237   0.002452
694      IT      vegetarian               28          12237   0.002288
647      IT        american               27          12237   0.002206
666      IT           grill               23          12237   0.001880
684      IT           salad               23          12237   0.001880
662      IT        dumpling               22          12237   0.001798
650      IT       breakfast               21          12237   0.001716
693      IT           vegan               21          12237   0.001716
655      IT        catering               20          12237   0.001634
673      IT           lunch               20          12237   0.001634
668      IT        hawaiian               18          12237   0.001471
651      IT          brunch               17          12237   0.001389
683      IT            rice               17          12237   0.001389
679      IT            pita               16          12237   0.001308
676      IT          noodle               15          12237   0.001226
692      IT            thai               15          12237   0.001226
687      IT     street food               14          12237   0.001144
674      IT   mediterranean               13          12237   0.001062
690      IT           tapas               13          12237   0.001062

## Generate a YAML friendly list of cuisine types

In [50]:
country_list = list(df_cuisine_agg['country'].unique())

In [51]:
for i in country_list:
    subset = df_cuisine_agg.loc[(df_cuisine_agg['country']==i) & (df_cuisine_agg['count_pct'] >= 0.01)]
    print(f"{i}: ")
    for j in subset['primary_cuisine']:
        print(f" - {j.title()}")

AT:
 - Bakery
 - Bar
 - Breakfast
 - Cafe
 - Fast Food
 - Grocery
 - Hotel
 - Other
 - Pizza
 - Supermarket
BE:
 - Bakery
 - Bar
 - Cafe
 - Coffee
 - Fast Food
 - Grocery
 - Hotel
 - Italian
 - Other
 - Pizza
 - Sandwich
 - Snack
 - Supermarket
BG:
 - Bakery
 - Bar
 - Cafe
 - Coffee
 - Fast Food
 - Grocery
 - Hotel
 - Other
 - Pizza
 - Supermarket
CA:
 - Bakery
 - Bar
 - Breakfast
 - Cafe
 - Chinese
 - Coffee
 - Dessert
 - Fast Food
 - Grocery
 - Hotel
 - Indian
 - Other
 - Pizza
 - Supermarket
 - Sushi
CH:
 - Bakery
 - Bar
 - Cafe
 - Coffee
 - Fast Food
 - Grocery
 - Hotel
 - Italian
 - Other
 - Pizza
 - Supermarket
 - Swiss
DE:
 - Bakery
 - Bar
 - Breakfast
 - Cafe
 - Coffee
 - Fast Food
 - German
 - Grocery
 - Hotel
 - Italian
 - Kebab
 - Other
 - Pizza
 - Snack
 - Supermarket
 - Sushi
DK:
 - Bakery
 - Bar
 - Burger
 - Cafe
 - Coffee
 - Fast Food
 - Grocery
 - Hotel
 - Other
 - Pizza
 - Supermarket
 - Sushi
ES:
 - Bakery
 - Bar
 - Burger
 - Cafe
 - Cafeteria
 - Chinese
 - Fast Food
 - Grocery
 - Indian
 - Italian
 - Kebab
 - Mexican
 - Other
 - Pizza
 - Supermarket
 - Sushi
 - Tapas
FR:
 - Bakery
 - Bar
 - Cafe
 - Coffee
 - Delicatessen
 - Fast Food
 - French
 - Grocery
 - Hotel
 - Organic
 - Other
 - Pizza
 - Supermarket
GB:
 - Bakery
 - Bar
 - Breakfast
 - Cafe
 - Chinese
 - Coffee
 - Dessert
 - Fast Food
 - Grocery
 - Hotel
 - Indian
 - Other
 - Pizza
 - Sandwich
 - Supermarket
IE:
 - Bakery
 - Bar
 - Breakfast
 - Cafe
 - Chinese
 - Coffee
 - Fast Food
 - Grocery
 - Hotel
 - Other
 - Pizza
 - Supermarket
IT:
 - Bar
 - Burger
 - Chinese
 - Delicatessen
 - Fast Food
 - Italian
 - Kebab
 - Other
 - Pizza
 - Poke Bowl
 - Sandwich
 - Supermarket
 - Sushi
LU:
 - European
 - Grocery
 - Other
 - Pizza
NL:
 - Bakery
 - Bar
 - Cafe
 - Cafeteria
 - Coffee
 - Diner
 - Fast Food
 - Grocery
 - Hotel
 - Lunch
 - Other
 - Pizza
 - Sandwich
 - Snack
 - Supermarket
 - Sushi
PL:
 - Bakery
 - Bar
 - Cafe
 - Coffee
 - Fast Food
 - Grocery
 - Hotel
 - Kebab
 - Other
 - Pizza
 - Supermarket
SK:
 - Bakery
 - Bar
 - Cafe
 - Coffee
 - Fast Food
 - Grocery
 - Hotel
 - Other
 - Pizza
 - Supermarket

# Check how many of the current opportunities will be mapped to the new cuisine types

In [32]:
## Get all opportunity snapshot
query = """
    SELECT *
    FROM `just-data-warehouse.sales_analytics_datamarts.global_sales_pipeline`
    WHERE source_system = 'Salesforce - Global' AND account_object_id IS NOT NULL
"""
query_job = client.query(query)
df_account = query_job.to_dataframe()

In [33]:
# Check the cuisine type matches by country
df_join = df_cuisine.merge(df_account[['google_place_id', 'restaurantid']], how='left', on='google_place_id')

In [34]:

df_country_count = df_join.groupby(['country'], as_index=False, dropna=True).agg({'restaurantid': 'nunique'})
df_country_count = df_country_count.rename(columns={'restaurantid':'total_count'})

df_count = df_join.groupby(['country', 'primary_cuisine'], as_index=False, dropna=False).agg({'restaurantid': 'nunique'}).sort_values('restaurantid', ascending=False)
df_count = df_count.merge(df_country_count, how='left', on='country')
df_count['count_pct'] = df_count['restaurantid'] / df_count['total_count']

In [38]:
df_count.loc[df_count['country']=='IT']

    country primary_cuisine  restaurantid  total_count  count_pct
315      IT           pizza            37          132   0.280303
402      IT           other            19          132   0.143939
434      IT             bar            13          132   0.098485
438      IT       fast food            12          132   0.090909
448      IT          burger            10          132   0.075758
468      IT       poke bowl             6          132   0.045455
483      IT        sandwich             5          132   0.037879
489      IT           kebab             4          132   0.030303
496      IT           sushi             4          132   0.030303
513      IT        hawaiian             3          132   0.022727
514      IT          indian             3          132   0.022727
518      IT          bakery             2          132   0.015152
532      IT         italian             2          132   0.015152
533      IT         mexican             2          132   0.015152
559      IT         dessert             1          132   0.007576
560      IT           grill             1          132   0.007576
561      IT           salad             1          132   0.007576
562      IT           pasta             1          132   0.007576
563      IT        japanese             1          132   0.007576
564      IT         grocery             1          132   0.007576
565      IT         seafood             1          132   0.007576
566      IT         chinese             1          132   0.007576
572      IT        american             1          132   0.007576
573      IT       breakfast             1          132   0.007576
691      IT    delicatessen             0          132   0.000000
692      IT          coffee             0          132   0.000000
693      IT        catering             0          132   0.000000
694      IT       cafeteria             0          132   0.000000
695      IT            cafe             0          132   0.000000
696      IT          brunch             0          132   0.000000
712      IT           diner             0          132   0.000000
715      IT           tapas             0          132   0.000000
716      IT     supermarket             0          132   0.000000
717      IT     street food             0          132   0.000000
718      IT            rice             0          132   0.000000
719      IT           ramen             0          132   0.000000
720      IT            pita             0          132   0.000000
721      IT          noodle             0          132   0.000000
722      IT   mediterranean             0          132   0.000000
723      IT           lunch             0          132   0.000000
724      IT       gastropub             0          132   0.000000
725      IT          fusion             0          132   0.000000
726      IT        dumpling             0          132   0.000000
727      IT           drink             0          132   0.000000
743      IT      vegetarian             0          132   0.000000
744      IT           vegan             0          132   0.000000
745      IT            thai             0          132   0.000000
746      IT             tea             0          132   0.000000

In [45]:
# Re-group cuisines that are very rare in the SF opportunities
df_count['primary_cuisine_new'] = np.where((df_count['restaurantid'] < 100) & (df_count['restaurantid'] < 0.001), 'other', df_count['primary_cuisine'])

In [47]:
df_count.loc[df_count['country'] == 'GB']

,country,primary_cuisine,restaurantid,total_count,count_pct,primary_cuisine_new
540,GB,fast food,1,2,0.5,fast food
557,GB,drink,1,2,0.5,drink
587,GB,buffet,0,2,0.0,other
588,GB,brunch,0,2,0.0,other
589,GB,breakfast,0,2,0.0,other
590,GB,brazilian,0,2,0.0,other
591,GB,bbq (barbecue),0,2,0.0,other
592,GB,bar,0,2,0.0,other
593,GB,bangladeshi,0,2,0.0,other
594,GB,bakery,0,2,0.0,other
595,GB,bagel,0,2,0.0,other
596,GB,american,0,2,0.0,other
597,GB,african,0,2,0.0,other
598,GB,100% halal,0,2,0.0,other
603,GB,street food,0,2,0.0,other
604,GB,sri lankan,0,2,0.0,other
605,GB,snack,0,2,0.0,other
606,GB,seafood,0,2,0.0,other
607,GB,sandwich,0,2,0.0,other
608,GB,salad,0,2,0.0,other
609,GB,romanian,0,2,0.0,other
610,GB,rice,0,2,0.0,other
611,GB,ramen,0,2,0.0,other
621,GB,wrap,0,2,0.0,other
622,GB,wok,0,2,0.0,other
623,GB,vietnamese,0,2,0.0,other
624,GB,vegetarian,0,2,0.0,other
625,GB,vegan,0,2,0.0,other
626,GB,turkish,0,2,0.0,other
627,GB,traditional,0,2,0.0,other
628,GB,thai,0,2,0.0,other
629,GB,tea,0,2,0.0,other
630,GB,tapas,0,2,0.0,other
631,GB,tandoori,0,2,0.0,other
632,GB,sweets,0,2,0.0,other
633,GB,sushi,0,2,0.0,other
634,GB,supermarket,0,2,0.0,other
667,GB,portuguese,0,2,0.0,other
668,GB,polish,0,2,0.0,other
669,GB,poke bowl,0,2,0.0,other
670,GB,pizza,0,2,0.0,other
671,GB,pita,0,2,0.0,other
672,GB,pasta,0,2,0.0,other
673,GB,pancake,0,2,0.0,other
674,GB,pakistani,0,2,0.0,other
675,GB,other,0,2,0.0,other
676,GB,organic,0,2,0.0,other
677,GB,noodle,0,2,0.0,other
678,GB,nepalese,0,2,0.0,other
679,GB,mexican,0,2,0.0,other
680,GB,mediterranean,0,2,0.0,other
681,GB,lunch,0,2,0.0,other
682,GB,lebanese,0,2,0.0,other
699,GB,japanese,0,2,0.0,other
700,GB,jamaican,0,2,0.0,other
701,GB,italian,0,2,0.0,other
702,GB,irish,0,2,0.0,other
703,GB,indian,0,2,0.0,other
704,GB,hotel,0,2,0.0,other
705,GB,halal,0,2,0.0,other
706,GB,gyro,0,2,0.0,other
707,GB,grocery,0,2,0.0,other
708,GB,grill,0,2,0.0,other
709,GB,greek,0,2,0.0,other
710,GB,gluten-free,0,2,0.0,other
711,GB,gastropub,0,2,0.0,other
728,GB,latin american,0,2,0.0,other
729,GB,korean,0,2,0.0,other
730,GB,kebab,0,2,0.0,other
763,GB,french,0,2,0.0,other
764,GB,fine dining,0,2,0.0,other
765,GB,european,0,2,0.0,other
766,GB,diner,0,2,0.0,other
767,GB,dessert,0,2,0.0,other
768,GB,delicatessen,0,2,0.0,other
769,GB,curry,0,2,0.0,other
770,GB,coffee,0,2,0.0,other
771,GB,cocktail,0,2,0.0,other
772,GB,chinese,0,2,0.0,other
773,GB,catering,0,2,0.0,other
774,GB,caribbean,0,2,0.0,other
775,GB,cafeteria,0,2,0.0,other
794,GB,fusion,0,2,0.0,other
825,GB,cafe,0,2,0.0,other
826,GB,burger,0,2,0.0,other

In [48]:
df_count.groupby(['country', 'primary_cuisine_new'], as_index=False).agg({'count_pct':'sum'})

    country primary_cuisine_new  count_pct
0        AT              bakery   0.032178
1        AT                 bar   0.028575
2        AT      bbq (barbecue)   0.002609
3        AT           breakfast   0.017642
4        AT              brunch   0.002609
..      ...                 ...        ...
579      SK               snack   0.003125
580      SK         supermarket   0.009375
581      SK               sushi   0.018750
582      SK                 tea   0.003125
583      SK          vietnamese   0.028125

[584 rows x 3 columns]

DE:
 - Italian
 - Pizza
 - Bakery
 - Bar
 - Coffee
 - Burger
 - Fast Food
 - Kebab
 - Turkish
 - German
 - Cafe
 - Greek
 - Grill
 - Indian
 - Chinese
 - Japanese
 - Vietnamese
 - Sushi
 - American
 - Vegan
 - Thai
PL:
 - Kebab
 - Pizza
 - Bar
 - Italian
 - Polish
 - Burger
 - Coffee
 - Cafe
 - Sushi
 - Turkish
 - Japanese
 - Bakery
 - Grill
 - American
 - Catering
 - Grocery
 - Fast Food
 - Indian
 - Thai
 - Vegan
 - Vietnamese
 - Dumpling
NL:
 - Cafe
 - Bar
 - Italian
 - Coffee
 - Chinese
 - Fast Food
 - Bakery
 - Pizza
 - Burger
 - Sushi
 - Grill
 - Turkish
 - Korean
 - Indian
 - Sandwich
 - Indonesian
 - Supermarket
 - Japanese
 - Greek
 - Lunch
 - Vegan
 - Diner
 - Thai
 - Catering
 - Surinamese
 - American
 - Cocktail
 - Bubble Tea
IE:
 - Pizza
 - Chinese
 - Indian
 - Burger
 - Coffee
 - Fast Food
 - Kebab
 - Cafe
 - Italian
 - American
 - Bar
 - Thai
 - Grill
 - Sandwich
 - Japanese
 - Irish
 - Mexican
 - Grocery
 - Bakery
nan:
AT:
 - Bakery
 - Pizza
 - Italian
 - Cafe
 - Bar
 - Fast Food
 - Kebab
 - Burger
 - Coffee
 - Chinese
 - Grill
 - American
 - Turkish
 - Vegan
 - Sandwich
 - Greek
 - Indian
 - European
 - Japanese
 - Supermarket
BE:
 - Pizza
 - Italian
 - Fast Food
 - Bar
 - Burger
 - Kebab
 - Bakery
 - Sandwich
 - Coffee
 - Chinese
 - Sushi
 - 100% Halal
 - Turkish
 - Snack
 - Grill
 - Japanese
 - Thai
 - Indian
 - Korean
 - Lebanese
 - French
 - Cafe
 - Greek
 - American
 - European
 - Hawaiian
 - Supermarket
BG:
 - Fast Food
 - Pizza
 - Bar
 - Grill
 - Bakery
 - Coffee
 - Burger
 - Bulgarian
 - Cafe
 - Italian
 - European
 - Hotel
 - Chinese
 - Breakfast
 - Sushi
 - Bbq (Barbecue)
 - Sandwich
 - Kebab
 - Turkish
CH:
 - Pizza
 - Italian
 - Bar
 - Kebab
 - Thai
 - Burger
 - Swiss
 - Indian
 - Japanese
 - Fast Food
 - Cafe
 - Sushi
 - Coffee
 - Chinese
 - Grill
 - Turkish
 - American
 - Mexican
 - Grocery
 - Bakery
 - Catering
 - Lebanese
 - Bubble Tea
DK:
 - Pizza
 - Italian
 - Burger
 - Grill
 - Cafe
 - Sushi
 - Thai
 - Indian
 - Kebab
 - Bagel
 - Sandwich
 - Chinese
 - Bbq (Barbecue)
 - Grocery
 - Coffee
 - Turkish
 - Japanese
 - Bar
 - Fast Food
 - Bakery
 - Vietnamese
 - Supermarket
 - Pasta
SK:
 - Pizza
 - Kebab
 - Bar
 - Fast Food
 - Italian
 - Vietnamese
 - Burger
 - Grocery
 - Cafe
 - Bakery
 - Organic
 - Grill
 - Chinese
 - Coffee
 - Delicatessen
 - Fusion
 - Buffet
 - Mediterranean
 - Sushi
FR:
 - Fast Food
 - Italian
 - Bakery
 - French
 - Pizza
 - Kebab
 - Turkish
 - American
 - Japanese
 - Lebanese
 - Mediterranean
 - Sandwich
 - Vegetarian
 - Argentinean
 - Catering
 - Food Truck
 - Coffee
 - Delicatessen
 - Burger
 - Bar
GB:
 - Burger
 - Grill
CA:
 - Dessert
 - Pizza
 - Burger

In [ ]:
# Make it formatted for yaml file